- hosts: ws-webserver

  post_tasks:
  - name: wait for webserver to come up
    wait_for: 'host{{ inventory_hostname }} port=22 state=started timeout=80'

  - name: install httpd
    package: name=httpd state=latest
    become: true

  - name: start httpd
    service: name=httpd state=running
    become: true
