---
#- name: wait for webserver to come up
#  wait_for: 'host{{ inventory_hostname }} port=22 state=started timeout=80'

- name: install httpd
  package: name=httpd state=latest
  become: true

- name: start httpd
  service: name=httpd state=started
  become: true

- name: stop firewall
  service: name=firewalld state=stopped enabled=no
  become: true
  ignore_errors: yes

- name: transfer index.html file
  copy:
    src: index.html
    dest: /var/www/html
    owner: apache
    group: apache

- name: transfer slide deck
  copy:
    src: files/decks/
    dest: /var/www/html/decks
    owner: apache
    group: apache

- name: copy license key
  copy:
    content: |
    {
     "company_name": "Red Hat", 
     "contact_email": "lrich@redhat.com", 
     "contact_name": "Lee Rich", 
     "hostname": "6eb115b6119a423d8d6a009ce1c18ccc", 
     "instance_count": 5, 
     "license_date": 1528906205, 
     "license_key": "cb99606081e80593b7c8af1bcc23cb4c9631bf92c19ba2433deb47aaddcab244", 
     "license_type": "enterprise", 
     "subscription_name": "Ansible Lightbulb Workshop", 
     "trial": true
    }
    dest: /var/www/html/ansible_tower_license.txt

- name: register with dynamic dns
  uri:
    url: http://freedns.afraid.org/dynamic/update.php?U1dFODUwTVRTTUlBQVNzTnpWSToxNzExMTAwMw==
    return_content: yes

- name: add dynamic dns to cron
  cron:
    name: "Update dns"
    minute: "0,10,20,30,40,50"
    job: "curl -k http://freedns.afraid.org/dynamic/update.php?U1dFODUwTVRTTUlBQVNzTnpWSToxNzExMTAwMw=="
