---
#- name: wait for webserver to come up
#  wait_for: 'host{{ inventory_hostname }} port=22 state=started timeout=80'

- name: install httpd
  package: name=httpd state=latest
  become: true

- name: start httpd
  service: name=httpd state=running
  become: true
  
- name: stop firewall
  service: name=firewalld state=stopped enabled=no
  become: true
  ignore_errors: yes

- name: transfer index.html file
  copy:
    src: index.html
    dest: /var/www/html
    owner: apache
    group: apache

- name: transfer slide deck
  copy:
    src: files/decks/
    dest: /var/www/html/decks
    owner: apache
    group: apache

- name: copy license key
  copy: 
    content: |
      {
      "company_name": "Red Hat, Inc.", 
      "contact_email": "kholmes@redhat.com", 
      "contact_name": "Kevin Holmes", 
      "hostname": "b055543e66264c038eb73656f406aba2", 
      "instance_count": 5, 
      "license_date": 1508340988, 
      "license_key": "4877f6ef15874461e8627c1f03f0edd2efbd6433a81dc43fb67dad124578d046", 
      "license_type": "enterprise", 
      "subscription_name": "Ansible Tower by Red Hat, Premium (5 Managed Nodes) NFR"
      }
    dest: /var/www/html/workshop-files/ansible_tower_license.txt

- name: register with dynamic dns
  uri:
    url: http://freedns.afraid.org/dynamic/update.php?U1dFODUwTVRTTUlBQVNzTnpWSToxNzExMTAwMw==
    return_content: yes
