---
#- name: wait for webserver to come up
#  wait_for: 'host{{ inventory_hostname }} port=22 state=started timeout=80'

- name: install httpd
  package: name=httpd state=latest
  become: true

- name: start httpd
  service: name=httpd state=running
  become: true
  
- name: stop firewall
  service: name=firewalld state=stopped enabled=no
  become: true
  ignore_errors: yes

- name: transfer index.html file
  copy:
    src: index.html
    dest: /var/www/html
    owner: apache
    group: apache

- name: transfer slide deck
  copy:
    src: files/decks/
    dest: /var/www/html
    owner: apache
    group: apache

- name: register with dynamic dns
  uri:
    url: http://freedns.afraid.org/dynamic/update.php?U1dFODUwTVRTTUlBQVNzTnpWSToxNzExMTAwMw==
    return_content: yes
