- name: Print out variables
  debug: msg="{{ item }}"
  with_items: "{{ instances.results }}"
  when: "'control' in item.invocation.module_args.instance_tags.Name"

- name: Print out public ip address
  debug: msg="{{ item.tagged_instances[0].public_ip }}"
  with_items: "{{ instances.results }}"
  when: "'control' in item.invocation.module_args.instance_tags.Name"

- name: Print out dns name
  debug: msg="{{ workshop_dns_zone }}"

- name: Create DNS name for each control node
  route53:
    state: present
    zone: "{{workshop_dnsa_zone}}"
    #region: "{{ec2_region}}"
    record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: CNAME
    overwrite: yes
    value: "{{ item.tagged_instances[0].public_ip }}"
    type: A
  with_items: "{{ groups.control_nodes }}"

- name: Break me here
  debug: msg="{{ broken_variable }}"
