---

- name: Create workspace template
  template:
    src: workspace.j2
    dest: ./workspace.txt

- name: Login to OnTap Instance
  uri:
    url:  http://{{ cloud_mgr }}:80/occm/api/auth/login
    method: POST
    body_format: json
    body: { "email": "{{ email_addr }}", "password": "{{ cloud_mgr_password }}" }
    status_code: 204
  register: login

- name: Create new working environment
  uri:
    url: http://{{ cloud_mgr }}:80/occm/api/vsa/working-environments
    method: POST
    body_format: json
    body: "{{ lookup('file','workspace.txt') }}"
    headers:
      Cookie: "{{ login.set_cookie }}"
    status_code: 204
