---

- name: Login to OnTap Instance
  uri:
    url:  http://107.20.112.232:80/occm/api/auth/login
    method: POST
    body_format: json
    body: 
    status_code: 204
  register: login

- name: Create new working environment
  uri:
    url: http://107.20.112.232:80/occm/api/vsa/working-environments
    method: POST
    body_format: json
    body: "{{ lookup('file','body_json') }}"
    headers:
      Cookie: "{{ login.set_cookie }}"
    status_code: 204
