- name: RHEL | Set version specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - always

#- name: RHEL | Install {{ firewall_name }} and libselinux-python
#  yum:
#    name:
#      - libselinux-python
#      - "{{ firewall_name }}"
#    state: present
#  register: install_packages
#  until: install_packages|success
#  delay: 3
#  retries: 5
#  tags:
#    - common

- name: Install nfs packages for storage workshop
  yum:
    name: nfs-utils
    state: present
  when: storage_workshop|d(False) == True

- name: RHEL | Disable SELinux
  selinux:
    state: permissive
    policy: targeted
  register: selinux_disable
  notify:
    - reboot
    - wait for instance
  tags:
    - common
  ignore_errors: yes

#- name: RHEL | Stop and disable firewall
#  service:
#    name: "{{ firewall_name }}"
#    state: stopped
#  tags:
#    - common
#  ignore_errors: yes
