---
- name: Make sure nodejs is installed
  yum:
    name: nodejs
    state: present

- name: Install Cloud Commander
  npm:
    name: cloudcmd
    global: yes
    state: present

- name: Run Cloud Commander
  shell: "(/usr/local/lib/npm/bin/cloudcmd -a -u "{{ username }}" -p r3dh4t --root /home/"{{ username }}" --one-panel-mode >/dev/null 2>&1 &)"
  register: myoutput
  become: true
  become_user: "{{ username }}"
