---
- name: Make sure nodejs is installed
  yum:
    name: nodejs
    state: present

- name: Install Cloud Commander
  npm:
    name: cloudcmd
    global: yes
    state: present

- name: Run Cloud Commander
  command: /usr/local/lib/npm/bin/cloudcmd --root /home/{{ username }} --one-panel-mode &
  register: myoutput
  become: true
  become_user: "{{ username }}"
