---

- name: generate users list
  set_fact:
    users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
  with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"

- name: Make sure nodejs is installed
  yum:
    name: nodejs
    state: present

- name: Install Cloud Commander
  npm:
    name: cloudcmd
    global: yes
    state: present

# SYSTEMD
- name: Template Systemd Service File for Cloudcmd
  become: yes
  template:
    src:   "cloudcmd.service.j2"
    dest:  "/etc/systemd/system/cloudcmd.service"
    group: root
    owner: root
    mode:  0644
  #notify: cloudcmd

- name: reload daemon
  become: yes
  command: systemctl daemon-reload
  #notify: cloudcmd

- name: enable cloudcmd service
  become: yes
  service:
    name: cloudcmd
    enabled: yes
    state: restarted
