#CREDENTIAL
- name: ADD CREDENTIAL INTO TOWER
  tower_credential:
    username: "{{ username }}"
    name: "Workshop Credential"
    #ssh_key_data: "{{ lookup('file', playbook_dir +'/' + ec2_name_prefix + '/' + ec2_name_prefix + '-private.pem') }}"
    kind: ssh
    password: "{{ workshop_password }}"
    organization: Default
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no

#PROJECT
# this displays warning, documented here: https://github.com/ansible/ansible/issues/60327
- name: ADD REPO INTO TOWER
  tower_project:
    name: "Workshop Project"
    organization: Default
    scm_type: git
    scm_url: "https://github.com/leerich/ansible-storage"
    scm_update_on_launch: true
    scm_clean: yes
    tower_username: admin
    tower_password: "{{ workshop_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no


#INVENTORY
- name: CREATE INVENTORY
  tower_inventory:
    name: "Workshop Inventory"
    organization: Default
    tower_username: admin
    tower_password: "{{ workshop_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no

- name: IMPORT INVENTORY
  command: "tower-manage inventory_import --source=/home/{{ username }}/lightbulb/lessons/lab_inventory/inventory --inventory-name='Workshop Inventory'"

#JOB TEMPLATES
- name: CREATE SVM JOB IN TOWER
  tower_job_template:
    name: "Create SVM and Interface"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "create-svm-interface.yml"
    credential: "Workshop Credential"
    state: "present"
    survey_enabled: false
    #survey_spec: "{{ lookup('template', 'user.json') }}"
    tower_username: admin
    tower_password: "{{ workshop_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no

- name: CREATE NFS JOB IN TOWER
  tower_job_template:
    name: "Enable NFS"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "enable-nfs.yml"
    credential: "Workshop Credential"
    state: "present"
    survey_enabled: false
    #survey_spec: "{{ lookup('template', 'user.json') }}"
    tower_username: admin
    tower_password: "{{ workshop_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no
  
