#PROJECT
# this displays warning, documented here: https://github.com/ansible/ansible/issues/60327
- name: ADD REPO INTO TOWER
  tower_project:
    name: "Workshop Project"
    organization: Default
    scm_type: git
    scm_url: "https://github.com/leerich/ansible-storage"
    scm_update_on_launch: true
    scm_clean: yes 
    tower_username: admin
    tower_password: "{{ workshop_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no


#INVENTORY
- name: CREATE INVENTORY
  tower_inventory:
    name: "Workshop Inventory"
    organization: Default
    tower_username: admin
    tower_password: "{{ workshop_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: no
  connection: local
  become: no

- name: IMPORT INVENTORY
  command: "tower-manage inventory_import --source=/home/{{ username }}/lightbulb/lessons/lab_inventory/inventory --inventory-name='Workshop Inventory'"
