- name: Install EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: install_epel
  until: install_epel|success
  delay: 3
  retries: 5
  tags:
    - control_node
    - control

- name: Install Base Repo
  copy:
    content: |
      [base]
      name=CentOS-$releasever - Base
      mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

      [updates]
      name=CentOS-$releasever - Updates
      mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
      #baseurl=http://mirror.centos.org/centos/$releasever/updates/$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

      #additional packages that may be useful
      [extras]
      name=CentOS-$releasever - Extras
      mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
      #baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      
      #additional packages that extend functionality of existing packages
      [centosplus]
      name=CentOS-$releasever - Plus
      mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
      #baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/
      gpgcheck=1
      enabled=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    dest: /etc/yum.repos.d/CentOS-Base.repo
    owner: root
    group: root
    tags:
    - control_node
    - control

- name: Install base packages
  yum:
    name:
      - vim
      - git
    state: latest
    enablerepo: epel-testing
  register: install_base_packages
  until: install_base_packages|success
  delay: 3
  retries: 5
  tags:
    - control_node
    - control

- name: Install Ansible
  yum:
    name:
      - sshpass
      - ansible
    state: latest
    enablerepo: epel-testing
  register: install_ansible
  until: install_ansible|success
  delay: 3
  retries: 5
  tags:
    - control_node
    - control
  when: control_node_install_ansible


- name: Clone lightbulb
  git:
    accept_hostkey: yes
    clone: yes
    dest: ~{{ username }}/lightbulb
    repo: https://github.com/ansible/lightbulb.git
    force: yes
  register: clone_lightbulb
  until: clone_lightbulb|success
  delay: 3
  retries: 5
  become_user: "{{ username }}"
  tags:
    - control_node
    - control

- name: Remove things that students don't need
  file:
    state: absent
    path: ~{{ username }}/lightbulb/{{ item }}
  with_items:
    - aws_lab_setup
    - resources
    - Vagrantfile
    - README.md
  tags:
    - control_node
    - control

- name: Install ansible.cfg and vimrc in home directory
  template:
    src: "{{ item }}"
    dest: ~{{ username }}/.{{ (item | splitext)[0] }}
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - ansible.cfg.j2
    - vimrc.j2
  tags:
    - control_node
    - control
    - vim

- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ username }}/lightbulb/lessons/lab_inventory
  tags:
    - control_node
    - control

- name: Put student inventory in proper spot
  copy:
    src: ./{{ username }}-instances.txt
    dest: "{{ control_node_inventory_path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: username in inventory_hostname
  tags:
    - control_node
    - control

