---
- hosts: "{{ host_pattern }}"
  become: true
  #gather_facts: false
  
  tasks:
    - name: remove duplicate packages
      yum: 
        name: "{{ item }}"
        state: absent
      with_items:
        - libgcc-4.8.5-16.el7.x86_64
        - glibc-common-2.17-196.el7.x86_64
      when: '"control" in ec2_tag_Name'
      
    - name: install needed packages
      yum:
        name: "{{item }}"
        state: installed
      with_items:
        - libgcc.i686
        - glibc.i686
      when: '"control" in ec2_tag_Name'
      
     - name: clean up rpm
       command: yum update -y
       when: '"control" in ec2_tag_Name'
