---

- hosts: "{{ host_addr }}"
  roles:
  - role: joe-speedboat.guacamole
    mariadb_db_host: 'localhost'
    mariadb_db_name: 'guacamole'
    mariadb_db_user: 'guacamole'
    mariadb_user_password: '.change-this_000.'
    mariadb_root_password: '.change-this_111.'
  tasks:
  - name: RHEL | Disable SELinux
    selinux:
      state: permissive
      policy: targeted
    register: selinux_disable
    #notify:
    #  - reboot
    #  - wait for instance
    tags:
      - common
    ignore_errors: yes

  - name: Copy user-mapping.xml file to guacamole directory
    copy:
      src: ./user-mapping.xml
      dest: /usr/share/tomcat/.guacamole
      owner: root
      group: tomcat
      mode: 0755
    notify: restart_guacamole

  -  debug: msg="trigger guacamole-restart"
     notify: restart_guacamole
     changed_when: true


  - name: Copy nginx configuration file
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/
      mode: 0644
    notify: restart nginx

  -  debug: msg="trigger nginx-restart"
     notify: restart nginx
     changed_when: true

  - name: install firewalld
    yum:
      name: firewalld
      state: present

  - name: start firewalld
    service:
      name: firewalld
      enabled: yes
      state: started

  - name: open https port on firewalld
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: open https port on firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: open https port on firewalld
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - 8080/tcp
      - 8081/tcp
      - 8000/tcp

  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes
      state: restarted
    ignore_errors: yes

  handlers:
    - name: restart_guacamole
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - guacd
        - tomcat

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

- name: Install certbot on guacamole server
  hosts: "{{ host_addr }}"
  gather_facts: false
  roles:
    - guacamole_certbot
  tags: guacamole
...
