---
- hosts: all
  roles:
  - role: joe-speedboat.guacamole
    mariadb_db_host: 'localhost'
    mariadb_db_name: 'guacamole'
    mariadb_db_user: 'guacamole'
    mariadb_user_password: '.change-this_000.'
    mariadb_root_password: '.change-this_111.'
  tasks:
  - name: RHEL | Disable SELinux
    selinux:
      state: permissive
      policy: targeted
    register: selinux_disable
    notify:
      - reboot
      - wait for instance
    tags:
      - common
    ignore_errors: yes

  - name: install firewalld
    yum:
      name: firewalld
      state: present

  - name: start firewalld
    service:
      name: firewalld
      enabled: yes
      state: started

  - name: open https port on firewalld
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: open https port on firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: open https port on firewalld
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - 8080/tcp
      - 8081/tcp
      - 8000/tcp

  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes
      state: restarted
    ignore_errors: yes
...
