---
- hosts: "{{ host_pattern }}"
  gather_facts: true

  roles:
    - { role: repo-epel, when: '"control" in ec2_tag_Name' }
    - { role: nodejs, when: '"control" in ec2_tag_Name' }
    - { role: wetty, when: '"control" in ec2_tag_Name' }
#    - { role: cloudcmd, when: '"control" in ec2_tag_Name' }
