---
- hosts: "{{ host_pattern }}"

  roles:
    - { role: repo-epel, when: '"control" in ec2_tag_Name' }
    - { role: nodejs, when: '"control" in ec2_tag_Name' }
    - { role: wetty, when: '"control" in ec2_tag_Name' }
