---
- name: Generate users list
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:
    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"


- name: Add hosts to control_nodes group
  add_host:
    name: "{{ item.invocation.module_args.instance_tags.Name }}"
    ansible_host: "{{ item.tagged_instances[0].public_ip }}"
    ansible_user: "{{ ec2_login_names[item.item.item.1.type] }}"
    ansible_port: "{{ ssh_port }}"
    groups: lab_hosts,control_nodes
  with_items: "{{ instances.results }}"
  when: "'control' in item.invocation.module_args.instance_tags.Name"
  #changed_when: no
  tags:
    - always
    - provision

- name: Set local username to create on instances
  set_fact:
    username: "{{ item | regex_replace('.*-(\\w*)-\\w*$','\\1') }}"
  with_items: "{{ groups.lab_hosts }}"
  delegate_to: "{{ item }}"
  delegate_facts: yes
  tags:
    - always
    - provision


- name: Install Cloud Commander
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - { role: cloudcmd, when: '"control" in ec2_tag_Name' }
