---
- hosts: localhost
  connection: local
  gather_facts: False
 
  tasks:

    - name: Provision a Webserver Instance
      ec2:
         #access_key: "{{ ec2_access_key }}"
         #secret_key: "{{ ec2_secret_key }}"
         key_name: "{{ ec2_keypair }}"
         group_id: "{{ ec2_security_group }}"
         instance_type: "{{ ec2_instance_type }}"
         image: "{{ ec2_image }}"
         region: "{{ ec2_region }}"
         vpc_subnet_id: "{{ ec2_vpc_subnet }}"
         #count: "{{ ec2_instance_count }}"
         wait: false
         assign_public_ip: yes
         exact_count: "{{ ec2_instance_count }}"
         count_tag:
            Name: Demo_Linux_Webserver
         instance_tags:
            ansible_group: WS-webservers
            Name: Demo_Linux_Webserver
      tags:
         - ws-webserver
      register: ec2
