- name: Remove environments
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:

    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"

    - name: Login to OnTap Instance
      uri:
        url:  http://204.236.211.203:80/occm/api/auth/login
        method: POST
        body_format: json
        body: { "email": "lrich00@gmail.com", "password": "password00!" }
        status_code: 204
      register: login

    - name: Get working environments
      uri:
        url: http://204.236.211.203:80/occm/api/vsa/working-environments
        method: Get
        validate_certs: no
        return_content: yes
        status_code: 200
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: working_environments

    - debug: var=working_environments

    - name: parse variable
      debug:
        var: item
      loop: "{{ working_environments | json_query('json[*].svmName') }}"

    - name: Show publicID
      debug:
        var: item
      with_nested:
        - "{{ working_environments | json_query(id_query) }}"
        - "{{ users }}"
      vars:
        id_query: "json[?svmName=='svm_{{ ec2_name_prefix }}_{{ item.0.username }}'].publicId"
      register: pubid

    - name: Display PubID
      debug: var=pubid.results[0].item

    - name: Remove working environment
      uri:
        url: http://204.236.211.203:80/occm/api/vsa/working-environments/
        method: Get
        validate_certs: no
        return_content: yes
        status_code: 200
        headers:
          Cookie: "{{ login.set_cookie }}"
