---


#- name: Create lab instances in AWS
#  hosts: localhost
#  connection: local
#  become: no
#  gather_facts: no
#  roles:
#    - manage_ec2_instances


- name: Provision Storage Resources
  hosts: all
  become: no
  gather_facts: no

  tasks:

    - name: Login to OnTap Instance
      uri:
        url:  http://{{ cloud_mgr }}:80/occm/api/auth/login
        method: POST
        body_format: json
        body: { "email": "{{ email_addr }}", "password": "{{ cloud_mgr_password }}" }
        status_code: 204
      register: login

    - name: Get Cluster Properties
      uri:
        url: https://{{ cloud_mgr }}:443/occm/api/vsa/working-environments?fields=clusterProperties
        method: Get
        validate_certs: no
        return_content: yes
        status_code: 200
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: clusterProperties

    - name: debug clusterProperties
      debug: var=clusterProperties
