- name: Generate users list
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:
    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"

- name: Destroy Route53 domain names for control nodes
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - name: Create DNS name for each control node
      route53:
        state: "{{ route53_state }}"
        zone: "{{workshop_dns_zone}}"
    #region: "{{ec2_region}}"
        record: "{{ec2_name_prefix|lower}}-{{ item.item.item[0].username }}.{{workshop_dns_zone}}"
        type: CNAME
        overwrite: yes
        value: "{{ item.tagged_instances[0].public_ip }}"
        type: A
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"
      #when: "'control' in item.invocation.module_args.instance_tags.Name"
  
  
- name: Destroy lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: yes

  vars:
    ec2_exact_count: 0
    ec2_wait: no

  roles:
    - manage_ec2_instances

  post_tasks:
    - name: Remove inventory files
      file: path="{{ item }}" state=absent
      with_fileglob: "{{ playbook_dir }}/*.txt"
      register: removal
      changed_when: removal|success
